WITH BANCOOB AS 
(SELECT CONVERT(CHAR(10), MBC.DTLANC,103) AS "Data",
(SELECT (ISNULL(SUM(MBC3.VLRLANC * MBC3.RECDESP),0)) FROM TGFMBC MBC3 INNER JOIN TSICTA CTA3 ON CTA3.CODCTABCOINT = MBC3.CODCTABCOINT
WHERE CTA3.CODCTABCOINT IN (14,15) AND MBC3.DTLANC >= DATEADD(month, DATEDIFF(month, 0,CONVERT(CHAR(10), MBC.DTLANC,103) ),0) AND MBC3.DTLANC < CONVERT(CHAR(10), MBC.DTLANC,103) AND NOT(MBC3.ORIGMOV = 'T' AND 
MBC3.CODCTABCOINT IN (14,15) AND 
MBC3.CODCTABCOCONTRA IN (14,15)))
 +
(SELECT SUM(SBC.SALDOREAL) FROM TGFSBC SBC WHERE SBC.CODCTABCOINT IN 
(14,15) AND SBC.REFERENCIA = DATEADD(month, DATEDIFF(month, 0, CONVERT(CHAR(10), MBC.DTLANC,103)),0)

) as SALDOCOOB,

       SUM((CASE WHEN MBC.RECDESP = 1 THEN  VLRLANC ELSE 0 END)) As "COOBCredito",
       SUM((CASE WHEN MBC.RECDESP = -1 THEN  VLRLANC ELSE 0 END)) As "COOBDebito"
FROM
    TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        LEFT JOIN TGFFIN FIN ON (MBC.NUBCO = FIN.NUBCO)
        LEFT JOIN TGFTIT TIT ON (FIN.CODTIPTIT = TIT.CODTIPTIT)
WHERE
   (( CONVERT(CHAR(07), MBC.DTLANC,102) = CONVERT(CHAR(07), :P_REFERENCIA,102)))
  AND CTA.CODCTABCOINT IN (14,15) AND NOT(MBC.ORIGMOV = 'T' AND MBC.CODCTABCOINT IN (14,15) AND MBC.CODCTABCOCONTRA IN (14,15))
GROUP BY CONVERT(CHAR(10), MBC.DTLANC,103)),

BRADESCO AS 
(SELECT CONVERT(CHAR(10), MBC.DTLANC,103) AS "Data",
(SELECT (ISNULL(SUM(MBC3.VLRLANC * MBC3.RECDESP),0)) FROM TGFMBC MBC3 INNER JOIN TSICTA CTA3 ON CTA3.CODCTABCOINT = MBC3.CODCTABCOINT
WHERE CTA3.CODCTABCOINT IN (12,13,18,28) AND MBC3.DTLANC >= DATEADD(month, DATEDIFF(month, 0,CONVERT(CHAR(10), MBC.DTLANC,103) ),0) AND MBC3.DTLANC < CONVERT(CHAR(10), MBC.DTLANC,103) AND NOT(MBC3.ORIGMOV = 'T' AND 
MBC3.CODCTABCOINT IN (12,13,18,28) AND 
MBC3.CODCTABCOCONTRA IN (12,13,18,28)))
 +
(SELECT SUM(SBC.SALDOREAL) FROM TGFSBC SBC WHERE SBC.CODCTABCOINT IN 
(12,13,18,28) AND SBC.REFERENCIA = DATEADD(month, DATEDIFF(month, 0, CONVERT(CHAR(10), MBC.DTLANC,103)),0)

) as SALDOBRAD,

       SUM((CASE WHEN MBC.RECDESP = 1 THEN  VLRLANC ELSE 0 END)) As "BRADCredito",
       SUM((CASE WHEN MBC.RECDESP = -1 THEN  VLRLANC ELSE 0 END)) As "BRADDebito"
FROM
    TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        LEFT JOIN TGFFIN FIN ON (MBC.NUBCO = FIN.NUBCO)
        LEFT JOIN TGFTIT TIT ON (FIN.CODTIPTIT = TIT.CODTIPTIT)
WHERE
   (( CONVERT(CHAR(07), MBC.DTLANC,102) = CONVERT(CHAR(07), :P_REFERENCIA,102)))
  AND CTA.CODCTABCOINT IN (12,13,18,28) AND NOT(MBC.ORIGMOV = 'T' AND MBC.CODCTABCOINT IN (14,15) AND MBC.CODCTABCOCONTRA IN (14,15))
GROUP BY CONVERT(CHAR(10), MBC.DTLANC,103)),

BMB AS 
(SELECT CONVERT(CHAR(10), MBC.DTLANC,103) AS "Data",
(SELECT (ISNULL(SUM(MBC3.VLRLANC * MBC3.RECDESP),0)) FROM TGFMBC MBC3 INNER JOIN TSICTA CTA3 ON CTA3.CODCTABCOINT = MBC3.CODCTABCOINT
WHERE CTA3.CODCTABCOINT IN (2,3,4) AND MBC3.DTLANC >= DATEADD(month, DATEDIFF(month, 0,CONVERT(CHAR(10), MBC.DTLANC,103) ),0) AND MBC3.DTLANC < CONVERT(CHAR(10), MBC.DTLANC,103) AND NOT(MBC3.ORIGMOV = 'T' AND 
MBC3.CODCTABCOINT IN (2,3,4) AND 
MBC3.CODCTABCOCONTRA IN (2,3,4)))
 +
(SELECT SUM(SBC.SALDOREAL) FROM TGFSBC SBC WHERE SBC.CODCTABCOINT IN 
(14,15) AND SBC.REFERENCIA = DATEADD(month, DATEDIFF(month, 0, CONVERT(CHAR(10), MBC.DTLANC,103)),0)

) as SALDOBMB,

       SUM((CASE WHEN MBC.RECDESP = 1 THEN  VLRLANC ELSE 0 END)) As "BMBCredito",
       SUM((CASE WHEN MBC.RECDESP = -1 THEN  VLRLANC ELSE 0 END)) As "BMBDebito"
FROM
    TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        LEFT JOIN TGFFIN FIN ON (MBC.NUBCO = FIN.NUBCO)
        LEFT JOIN TGFTIT TIT ON (FIN.CODTIPTIT = TIT.CODTIPTIT)
WHERE
   (( CONVERT(CHAR(07), MBC.DTLANC,102) = CONVERT(CHAR(07), :P_REFERENCIA,102)))
  AND CTA.CODCTABCOINT IN (2,3,4) AND NOT(MBC.ORIGMOV = 'T' AND MBC.CODCTABCOINT IN (2,3,4) AND MBC.CODCTABCOCONTRA IN (2,3,4))
GROUP BY CONVERT(CHAR(10), MBC.DTLANC,103)),

ITAU AS 
(SELECT CONVERT(CHAR(10), MBC.DTLANC,103) AS "Data",
(SELECT (ISNULL(SUM(MBC3.VLRLANC * MBC3.RECDESP),0)) FROM TGFMBC MBC3 INNER JOIN TSICTA CTA3 ON CTA3.CODCTABCOINT = MBC3.CODCTABCOINT
WHERE CTA3.CODCTABCOINT IN (5,6,7,8,9) AND MBC3.DTLANC >= DATEADD(month, DATEDIFF(month, 0,CONVERT(CHAR(10), MBC.DTLANC,103) ),0) AND MBC3.DTLANC < CONVERT(CHAR(10), MBC.DTLANC,103) AND NOT(MBC3.ORIGMOV = 'T' AND 
MBC3.CODCTABCOINT IN (5,6,7,8,9) AND 
MBC3.CODCTABCOCONTRA IN (5,6,7,8,9)))
 +
(SELECT SUM(SBC.SALDOREAL) FROM TGFSBC SBC WHERE SBC.CODCTABCOINT IN 
(5,6,7,8,9) AND SBC.REFERENCIA = DATEADD(month, DATEDIFF(month, 0, CONVERT(CHAR(10), MBC.DTLANC,103)),0)

) as SALDOITAU,

       SUM((CASE WHEN MBC.RECDESP = 1 THEN  VLRLANC ELSE 0 END)) As "ITAUCredito",
       SUM((CASE WHEN MBC.RECDESP = -1 THEN  VLRLANC ELSE 0 END)) As "ITAUDebito"
FROM
    TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        LEFT JOIN TGFFIN FIN ON (MBC.NUBCO = FIN.NUBCO)
        LEFT JOIN TGFTIT TIT ON (FIN.CODTIPTIT = TIT.CODTIPTIT)
WHERE
   (( CONVERT(CHAR(07), MBC.DTLANC,102) = CONVERT(CHAR(07), :P_REFERENCIA,102)))
  AND CTA.CODCTABCOINT IN (5,6,7,8,9) AND NOT(MBC.ORIGMOV = 'T' AND MBC.CODCTABCOINT IN (5,6,7,8,9) AND MBC.CODCTABCOCONTRA IN (5,6,7,8,9))
GROUP BY CONVERT(CHAR(10), MBC.DTLANC,103)),

CEF AS 
(SELECT CONVERT(CHAR(10), MBC.DTLANC,103) AS "Data",
(SELECT (ISNULL(SUM(MBC3.VLRLANC * MBC3.RECDESP),0)) FROM TGFMBC MBC3 INNER JOIN TSICTA CTA3 ON CTA3.CODCTABCOINT = MBC3.CODCTABCOINT
WHERE CTA3.CODCTABCOINT IN (10,11) AND MBC3.DTLANC >= DATEADD(month, DATEDIFF(month, 0,CONVERT(CHAR(10), MBC.DTLANC,103) ),0) AND MBC3.DTLANC < CONVERT(CHAR(10), MBC.DTLANC,103) AND NOT(MBC3.ORIGMOV = 'T' AND 
MBC3.CODCTABCOINT IN (10,11) AND 
MBC3.CODCTABCOCONTRA IN (10,11)))
 +
(SELECT SUM(SBC.SALDOREAL) FROM TGFSBC SBC WHERE SBC.CODCTABCOINT IN 
(10,11) AND SBC.REFERENCIA = DATEADD(month, DATEDIFF(month, 0, CONVERT(CHAR(10), MBC.DTLANC,103)),0)

) as SALDOCEF,

       SUM((CASE WHEN MBC.RECDESP = 1 THEN  VLRLANC ELSE 0 END)) As "CEFCredito",
       SUM((CASE WHEN MBC.RECDESP = -1 THEN  VLRLANC ELSE 0 END)) As "CEFDebito"
FROM
    TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        LEFT JOIN TGFFIN FIN ON (MBC.NUBCO = FIN.NUBCO)
        LEFT JOIN TGFTIT TIT ON (FIN.CODTIPTIT = TIT.CODTIPTIT)
WHERE
   (( CONVERT(CHAR(07), MBC.DTLANC,102) = CONVERT(CHAR(07), :P_REFERENCIA,102)))
  AND CTA.CODCTABCOINT IN (10,11) AND NOT(MBC.ORIGMOV = 'T' AND MBC.CODCTABCOINT IN (10,11) AND MBC.CODCTABCOCONTRA IN (10,11))
GROUP BY CONVERT(CHAR(10), MBC.DTLANC,103))

SELECT DISTINCT 
    A.*, COALESCE(A.DATA, B.DATA, C.DATA, D.DATA, E.DATA) AS DATA_COMPLETA, 
    (SELECT SUM(COALESCE(D.SALDOCOOB,0) + COALESCE(D.COOBCredito,0) - COALESCE(D.COOBDebito,0)) AS NOVOSALDO
     FROM BANCOOB D
     WHERE D.DATA = (
         SELECT COALESCE(
             (SELECT MAX(D2.DATA) FROM BANCOOB D2 WHERE D2.DATA <= COALESCE(A.DATA, B.DATA, C.DATA, E.DATA)),
             (SELECT MIN(D2.DATA) FROM BANCOOB D2)
         )
     )
     GROUP BY D.DATA
    ) AS SALDOCOOB,
(SELECT SUM(COALESCE(B1.SALDOBRAD,0) + COALESCE(B1.BRADCREDITO,0) - COALESCE(B1.BRADDEBITO,0)) AS NOVOSALDO
 FROM BRADESCO B1
 WHERE B1.DATA = (
     SELECT COALESCE(
         (SELECT MAX(B2.DATA) FROM BRADESCO B2 WHERE B2.DATA <= COALESCE(A.DATA, B.DATA, C.DATA, E.DATA)),
         (SELECT MIN(B2.DATA) FROM BRADESCO B2)
     )
 )
 GROUP BY B1.DATA
) AS SALDOBRAD,
(SELECT SUM(COALESCE(C1.SALDOBMB,0) + COALESCE(C1.BMBCREDITO,0) - COALESCE(C1.BMBDEBITO,0)) AS NOVOSALDO
 FROM BMB C1
 WHERE C1.DATA = (
     SELECT COALESCE(
         (SELECT MAX(C2.DATA) FROM BMB C2 WHERE C2.DATA <= COALESCE(A.DATA, B.DATA, C.DATA, E.DATA)),
         (SELECT MIN(C2.DATA) FROM BMB C2)
     )
 )
 GROUP BY C1.DATA
) AS SALDOBMB,
(SELECT SUM(COALESCE(E1.SALDOCEF,0) + COALESCE(E1.CEFCREDITO,0) - COALESCE(E1.CEFDEBITO,0)) AS NOVOSALDO
 FROM CEF E1
 WHERE E1.DATA = (
     SELECT COALESCE(
         (SELECT MAX(E2.DATA) FROM CEF E2 WHERE E2.DATA <= COALESCE(A.DATA, B.DATA, C.DATA, E.DATA)),
         (SELECT MIN(E2.DATA) FROM CEF E2)
     )
 )
 GROUP BY E1.DATA
) AS SALDOCEF

FROM ITAU A
LEFT JOIN BRADESCO B ON A.DATA=B.DATA
LEFT JOIN BMB C ON A.DATA=C.DATA
LEFT JOIN BANCOOB D ON A.DATA=D.DATA
LEFT JOIN CEF E ON A.DATA=E.DATA

GROUP BY A.DATA, B.DATA, C.DATA, D.DATA, E.DATA, A.SALDOITAU, A.ITAUCREDITO, A.ITAUDEBITO, B.SALDOBRAD, B.BRADCREDITO, B.BRADDEBITO, C.SALDOBMB, C.BMBCREDITO, C.BMBDEBITO, D.SALDOCOOB, D.COOBCREDITO, D.COOBDEBITO, E.SALDOCEF, E.CEFCREDITO,E.CEFDEBITO